"""Reporte diario de navegación por correo.

Al final del día (hora configurable, en la zona horaria de la instalación) se
manda a los administradores que tengan correo un resumen de las últimas 24 h:
usuarios activos, sitios, datos y peticiones, tops de usuarios y sitios, sitios
bloqueados más intentados, cuotas agotadas y alertas detectadas.

Solo se puede activar si hay SMTP configurado y al menos un administrador con
correo (ver `condiciones`). Los datos salen de los mismos agregados por hora que
alimentan Actividad de red, así que generarlo es instantáneo.
"""
import html
import logging
import threading
import time
from datetime import datetime

from sqlalchemy import text

from app.database import SessionLocal
from app.services import rollup_service as ru
from app.services import timezone_service as tzs

logger = logging.getLogger(__name__)

_POLL = 30
_CLAVE_ULTIMO = "report:ultimo_envio"
_CLAVE_IDIOMA = "report_lang"

_T = {
    "es": {
        "titulo": "Reporte diario de navegación", "desde": "Periodo", "usuarios": "Usuarios activos",
        "sitios": "Sitios visitados", "datos": "Datos consumidos", "peticiones": "Peticiones atendidas",
        "bloqueadas": "Bloqueadas", "cache": "Aciertos de caché",
        "top_usuarios": "Usuarios que más navegaron", "top_sitios": "Sitios más visitados",
        "top_bloq": "Sitios bloqueados más intentados", "top_bloq_u": "Usuarios con más bloqueos",
        "cuotas": "Cuotas agotadas", "alertas": "Alertas y anomalías", "nada": "Sin datos",
        "sin_cuotas": "Ninguna cuota se agotó.", "sin_alertas": "No se detectó ninguna anomalía.",
        "req": "peticiones", "cortada": "acceso cortado", "limitada": "velocidad limitada", "activa": "sin acción",
        "pie": "Generado por SquidManager. Se envía cada día a esta hora; se configura en Notificaciones.",
        "asunto": "Reporte diario de navegación", "usuario": "usuario", "grupo": "grupo",
    },
    "en": {
        "titulo": "Daily browsing report", "desde": "Period", "usuarios": "Active users",
        "sitios": "Sites visited", "datos": "Data used", "peticiones": "Requests served",
        "bloqueadas": "Blocked", "cache": "Cache hits",
        "top_usuarios": "Top users by browsing", "top_sitios": "Most visited sites",
        "top_bloq": "Most attempted blocked sites", "top_bloq_u": "Users with most blocks",
        "cuotas": "Quotas reached", "alertas": "Alerts and anomalies", "nada": "No data",
        "sin_cuotas": "No quota was reached.", "sin_alertas": "No anomaly was detected.",
        "req": "requests", "cortada": "access cut", "limitada": "speed limited", "activa": "no action",
        "pie": "Generated by SquidManager. Sent every day at this time; configure it in Notifications.",
        "asunto": "Daily browsing report", "usuario": "user", "grupo": "group",
    },
    "pt": {
        "titulo": "Relatório diário de navegação", "desde": "Período", "usuarios": "Usuários ativos",
        "sitios": "Sites visitados", "datos": "Dados consumidos", "peticiones": "Requisições atendidas",
        "bloqueadas": "Bloqueadas", "cache": "Acertos de cache",
        "top_usuarios": "Usuários que mais navegaram", "top_sitios": "Sites mais visitados",
        "top_bloq": "Sites bloqueados mais tentados", "top_bloq_u": "Usuários com mais bloqueios",
        "cuotas": "Cotas esgotadas", "alertas": "Alertas e anomalias", "nada": "Sem dados",
        "sin_cuotas": "Nenhuma cota foi esgotada.", "sin_alertas": "Nenhuma anomalia foi detectada.",
        "req": "requisições", "cortada": "acesso cortado", "limitada": "velocidade limitada", "activa": "sem ação",
        "pie": "Gerado pelo SquidManager. Enviado todos os dias neste horário; configure em Notificações.",
        "asunto": "Relatório diário de navegação", "usuario": "usuário", "grupo": "grupo",
    },
}


def _fmt_bytes(n: float) -> str:
    n = float(n or 0)
    for u in ("B", "KB", "MB", "GB", "TB"):
        if abs(n) < 1024 or u == "TB":
            return f"{n:.0f} {u}" if u == "B" else f"{n:.1f} {u}"
        n /= 1024
    return f"{n:.1f} TB"


def _fmt_n(n) -> str:
    return f"{int(n):,}".replace(",", ".")


# ---------------------------------------------------------------------------
# Estado y condiciones
# ---------------------------------------------------------------------------

def _app_get(db, k: str) -> str | None:
    r = db.execute(text("SELECT v FROM app_settings WHERE k=:k"), {"k": k}).fetchone()
    return r[0] if r else None


def _app_set(db, k: str, v: str) -> None:
    db.execute(text("INSERT INTO app_settings (k,v) VALUES (:k,:v) ON CONFLICT (k) DO UPDATE SET v=EXCLUDED.v"),
               {"k": k, "v": v})


def guardar_idioma(db, idioma: str) -> None:
    if idioma in _T:
        _app_set(db, _CLAVE_IDIOMA, idioma)


def destinatarios(db) -> list[str]:
    from app.models.admin import Admin
    return sorted({a.email.strip() for a in db.query(Admin).filter(Admin.is_active == True).all()  # noqa: E712
                   if a.email and "@" in a.email})


def condiciones(db) -> dict:
    """Qué falta para poder activar el reporte."""
    from app.models.smtp_config import SmtpConfig
    smtp = db.query(SmtpConfig).first()
    smtp_ok = bool(smtp and smtp.smtp_host and (smtp.smtp_from or smtp.smtp_user))
    dest = destinatarios(db)
    return {"smtp": smtp_ok, "admin_con_email": bool(dest), "destinatarios": dest, "ok": smtp_ok and bool(dest)}


# ---------------------------------------------------------------------------
# Contenido
# ---------------------------------------------------------------------------

def recopilar(db, segundos: int = 86400) -> dict:
    tot = ru.totales_actividad(segundos, None, None)
    top_u = ru.top_users(5, "bytes", segundos, None, None)
    top_d = ru.top_domains(5, False, "bytes", segundos, None, None)
    top_bd = ru.top_domains(5, True, "requests", segundos, None, None)
    top_bu, _sin = ru.top_blocked_users(5, segundos, None, None)
    cache = ru.cache_resumen(segundos, None, None)
    req = int(sum(x["requests"] for x in ru.serie_total(segundos, None, None)))
    desde = time.time() - segundos

    from app.services.quota_service import cuotas_excedidas
    cuotas = [c for c in cuotas_excedidas(db) if (c.get("excedida_en") or 0) >= desde or c.get("excedida_en") is None]

    from app.services.anomaly_service import get_anomalias_recientes
    alertas = get_anomalias_recientes(segundos / 3600, 15)
    return {
        "totales": tot, "peticiones": req, "cache": cache,
        "top_usuarios": top_u, "top_sitios": top_d, "top_bloqueados": top_bd, "top_bloqueos_usuarios": top_bu,
        "cuotas": cuotas, "alertas": alertas,
    }


def _tabla(filas: list[tuple[str, str]], vacio: str) -> str:
    if not filas:
        return f'<p style="margin:0;color:#6b7c88;font-size:13px">{html.escape(vacio)}</p>'
    out = ['<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="font-size:13px">']
    for i, (a, b) in enumerate(filas):
        bg = "#f5f9fc" if i % 2 == 0 else "#ffffff"
        out.append(
            f'<tr style="background:{bg}"><td style="padding:7px 10px;color:#1c2b36">{html.escape(a)}</td>'
            f'<td style="padding:7px 10px;text-align:right;color:#0B497C;font-weight:600;white-space:nowrap">{html.escape(b)}</td></tr>'
        )
    out.append("</table>")
    return "".join(out)


def _seccion(titulo: str, cuerpo: str) -> str:
    return (f'<div style="margin:0 0 22px"><h3 style="margin:0 0 8px;font-size:14px;color:#0B497C;'
            f'border-bottom:2px solid #e3edf4;padding-bottom:5px">{html.escape(titulo)}</h3>{cuerpo}</div>')


def _tarjeta(valor: str, etiqueta: str) -> str:
    return (f'<td style="width:33%;padding:6px"><div style="background:#f0f6fb;border-radius:10px;padding:14px 8px;text-align:center">'
            f'<div style="font-size:22px;font-weight:700;color:#0B497C">{html.escape(valor)}</div>'
            f'<div style="font-size:11.5px;color:#56697a;margin-top:2px">{html.escape(etiqueta)}</div></div></td>')


def construir(datos: dict, idioma: str = "es", ahora: datetime | None = None) -> tuple[str, str, str]:
    """(asunto, html, texto plano)."""
    t = _T.get(idioma, _T["es"])
    ahora = ahora or tzs.ahora_local()
    fecha = ahora.strftime("%Y-%m-%d %H:%M")
    tot = datos["totales"]
    d = datos

    tarjetas = (
        "<tr>" + _tarjeta(_fmt_n(tot["usuarios"]["count"]), t["usuarios"])
        + _tarjeta(_fmt_n(tot["dominios"]["count"]), t["sitios"])
        + _tarjeta(_fmt_bytes(tot["usuarios"]["bytes"]), t["datos"]) + "</tr><tr>"
        + _tarjeta(_fmt_n(d["peticiones"]), t["peticiones"])
        + _tarjeta(_fmt_n(tot["usuarios_bloqueados_requests"]), t["bloqueadas"])
        + _tarjeta(f'{d["cache"]["cache_hit_ratio"]} %' if d["cache"]["cache_hit_ratio"] is not None else "—", t["cache"]) + "</tr>"
    )
    req = t["req"]
    cuotas = []
    for c in d["cuotas"]:
        est = t["cortada"] if c["quota_action_applied"] and c["quota_action"] == "cut" else (
            t["limitada"] if c["quota_action_applied"] else t["activa"])
        cuotas.append((f'{c["nombre"]} ({t[c["tipo"]]})', f'{_fmt_bytes(c["quota_bytes_used"])} / {_fmt_bytes(c["quota_bytes"])} · {est}'))
    alertas = [(a["asunto"].replace("SquidManager: ", ""), a["mensaje"][:110]) for a in d["alertas"]]

    cuerpo = (
        f'<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin:0 0 20px">{tarjetas}</table>'
        + _seccion(t["top_usuarios"], _tabla([(u["user"], f'{_fmt_bytes(u["bytes"])} · {_fmt_n(u["requests"])} {req}') for u in d["top_usuarios"]], t["nada"]))
        + _seccion(t["top_sitios"], _tabla([(x["domain"], f'{_fmt_bytes(x["bytes"])} · {_fmt_n(x["requests"])} {req}') for x in d["top_sitios"]], t["nada"]))
        + _seccion(t["top_bloq"], _tabla([(x["domain"], f'{_fmt_n(x["requests"])} {req}') for x in d["top_bloqueados"]], t["nada"]))
        + _seccion(t["top_bloq_u"], _tabla([(u, _fmt_n(n)) for u, n in d["top_bloqueos_usuarios"]], t["nada"]))
        + _seccion(t["cuotas"], _tabla(cuotas, t["sin_cuotas"]))
        + _seccion(t["alertas"], _tabla(alertas, t["sin_alertas"]))
    )
    cuerpo_html = (
        '<!doctype html><html><body style="margin:0;background:#eef3f7;font-family:Segoe UI,Helvetica,Arial,sans-serif">'
        '<table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" style="padding:24px 12px">'
        '<table role="presentation" width="620" cellspacing="0" cellpadding="0" style="max-width:620px;background:#fff;border-radius:14px;overflow:hidden">'
        f'<tr><td style="background:#0B497C;padding:22px 26px"><div style="color:#fff;font-size:20px;font-weight:700">{html.escape(t["titulo"])}</div>'
        f'<div style="color:#b9d3e6;font-size:12.5px;margin-top:4px">{html.escape(t["desde"])}: 24 h · {html.escape(fecha)} ({html.escape(str(tzs.get_tz()))})</div></td></tr>'
        f'<tr><td style="padding:22px 26px">{cuerpo}</td></tr>'
        f'<tr><td style="padding:14px 26px;background:#f5f9fc;color:#7a8b97;font-size:11.5px">{html.escape(t["pie"])}</td></tr>'
        "</table></td></tr></table></body></html>"
    )

    lineas = [t["titulo"], f'{t["desde"]}: 24 h · {fecha}', "",
              f'{t["usuarios"]}: {tot["usuarios"]["count"]}', f'{t["sitios"]}: {tot["dominios"]["count"]}',
              f'{t["datos"]}: {_fmt_bytes(tot["usuarios"]["bytes"])}', f'{t["peticiones"]}: {d["peticiones"]}',
              f'{t["bloqueadas"]}: {tot["usuarios_bloqueados_requests"]}', ""]
    for titulo, filas in (
        (t["top_usuarios"], [(u["user"], _fmt_bytes(u["bytes"])) for u in d["top_usuarios"]]),
        (t["top_sitios"], [(x["domain"], _fmt_bytes(x["bytes"])) for x in d["top_sitios"]]),
        (t["top_bloq"], [(x["domain"], str(x["requests"])) for x in d["top_bloqueados"]]),
        (t["cuotas"], cuotas), (t["alertas"], alertas)):
        lineas.append(titulo + ":")
        lineas += [f"  - {a}: {b}" for a, b in filas] or ["  -"]
        lineas.append("")
    return f'SquidManager: {t["asunto"]} {ahora.strftime("%Y-%m-%d")}', cuerpo_html, "\n".join(lineas)


# ---------------------------------------------------------------------------
# Envío y planificación
# ---------------------------------------------------------------------------

def enviar(db, forzar: bool = False) -> dict:
    from app.models.smtp_config import SmtpConfig
    from app.services.notification_service import _enviar_smtp, _snapshot_config
    from app.models.notification_config import NotificationConfig

    cond = condiciones(db)
    if not cond["ok"]:
        return {"ok": False, "message": "Falta configurar el SMTP o un correo en la cuenta de administrador"}
    cfg = db.query(NotificationConfig).first()
    smtp = db.query(SmtpConfig).first()
    snap = _snapshot_config(cfg, smtp)
    idioma = _app_get(db, _CLAVE_IDIOMA) or "es"
    asunto, cuerpo_html, texto = construir(recopilar(db), idioma)
    ok, msg = _enviar_smtp(snap, cond["destinatarios"], asunto, texto, html_body=cuerpo_html)
    return {"ok": ok, "message": msg}


def _tick() -> None:
    db = SessionLocal()
    try:
        from app.models.notification_config import NotificationConfig
        cfg = db.query(NotificationConfig).first()
        if not cfg or not cfg.daily_report_enabled:
            return
        ahora = tzs.ahora_local()
        try:
            hh, mm = (int(x) for x in (cfg.daily_report_time or "23:55").split(":"))
        except ValueError:
            hh, mm = 23, 55
        hoy = ahora.strftime("%Y-%m-%d")
        if _app_get(db, _CLAVE_ULTIMO) == hoy:
            return
        if (ahora.hour, ahora.minute) < (hh, mm):
            return
        # Marca primero: si el envío falla no se reintenta cada 30 s durante todo el día.
        _app_set(db, _CLAVE_ULTIMO, hoy)
        db.commit()
        r = enviar(db)
        if r["ok"]:
            logger.info("Reporte diario enviado: %s", r["message"])
        else:
            logger.warning("Reporte diario no enviado: %s", r["message"])
    finally:
        db.close()


def _loop() -> None:
    time.sleep(20)
    while True:
        try:
            _tick()
        except Exception as e:
            logger.error("Error en el reporte diario: %s", e)
        time.sleep(_POLL)


def start_daily_report() -> None:
    threading.Thread(target=_loop, name="daily-report", daemon=True).start()
