// Contenido del artículo "Kerberos" de la biblioteca de Documentación.
// Ver docsActividadRed.ts para la razón de que esto viva aparte de los
// diccionarios de i18n/*.json.
export const DOC_KERBEROS: Record<'es' | 'en' | 'pt', string> = {
  es: `
## Para qué sirve

Autenticación **transparente** (single sign-on): un usuario de dominio Windows navega sin que el navegador le pida usuario y contraseña, porque su sesión de Windows ya demuestra quién es. Coexiste con Basic (usuario/contraseña) -activarlo no la reemplaza, solo ofrece Negotiate como opción adicional.

## Lo que hace falta antes de activarlo

1. Un registro DNS que resuelva el FQDN del proxy, coincidiendo con el SPN del keytab (\`HTTP/fqdn\`).
2. Un **keytab** generado por el administrador del Active Directory -SquidManager no lo genera, lo recibe.

## El script de PowerShell

Para no depender de que alguien copie a mano el procedimiento de \`ktpass\` (el error más común: olvidarse de cambiar el Realm o el FQDN del ejemplo por los propios), el panel genera un script ya completado con esos dos valores. Hay que revisarlo antes de correrlo -se ejecuta con permisos de administrador de dominio- y correrlo en una máquina con el módulo ActiveDirectory (RSAT) y \`ktpass\` disponibles. No incluye ninguna contraseña: la pide por consola al ejecutarse.

## Subir el keytab

El archivo que genera ese script (o que ya tenga el administrador del dominio) se sube desde acá. Tiene que cubrir todos los tipos de cifrado (\`-crypto All\`): el tipo real que use el controlador de dominio no se puede predecir de antemano, y un keytab que solo cubre uno falla en silencio con clientes que negocian otro.

Sin keytab subido, Kerberos no se ofrece aunque esté marcado como activado. Después de subirlo (o borrarlo), hace falta **Aplicar cambios** para que Squid empiece a usarlo.
`.trim(),
  en: `
## What this is for

**Transparent** authentication (single sign-on): a Windows domain user browses without the browser asking for a username and password, because their Windows session already proves who they are. It coexists with Basic (username/password) -turning it on doesn't replace it, it just offers Negotiate as an extra option.

## What's needed before turning it on

1. A DNS record that resolves the proxy's FQDN, matching the keytab's SPN (\`HTTP/fqdn\`).
2. A **keytab** generated by the Active Directory administrator -SquidManager doesn't generate it, it receives it.

## The PowerShell script

To avoid depending on someone copying the \`ktpass\` procedure by hand (the most common mistake: forgetting to change the example's Realm or FQDN for the real ones), the panel generates a script already filled in with those two values. It should be reviewed before running -it runs with domain admin permissions- and run on a machine with the ActiveDirectory module (RSAT) and \`ktpass\` available. It doesn't include any password: it asks for it on the console when run.

## Uploading the keytab

The file that script generates (or one the domain admin already has) is uploaded from here. It has to cover all encryption types (\`-crypto All\`): the real type the domain controller will use can't be predicted ahead of time, and a keytab that only covers one fails silently with clients that negotiate another.

Without a keytab uploaded, Kerberos isn't offered even if marked as enabled. After uploading it (or deleting it), **Apply changes** is needed for Squid to start using it.
`.trim(),
  pt: `
## Para que serve

Autenticação **transparente** (single sign-on): um usuário de domínio Windows navega sem que o navegador peça usuário e senha, porque sua sessão do Windows já comprova quem ele é. Coexiste com Basic (usuário/senha) -ativá-lo não a substitui, só oferece Negotiate como opção adicional.

## O que é necessário antes de ativar

1. Um registro DNS que resolva o FQDN do proxy, coincidindo com o SPN do keytab (\`HTTP/fqdn\`).
2. Um **keytab** gerado pelo administrador do Active Directory -o SquidManager não o gera, ele o recebe.

## O script do PowerShell

Para não depender de alguém copiar manualmente o procedimento do \`ktpass\` (o erro mais comum: esquecer de trocar o Realm ou o FQDN do exemplo pelos próprios), o painel gera um script já preenchido com esses dois valores. É preciso revisá-lo antes de rodar -ele roda com permissões de administrador de domínio- e executá-lo em uma máquina com o módulo ActiveDirectory (RSAT) e \`ktpass\` disponíveis. Não inclui nenhuma senha: ela é pedida no console ao executar.

## Enviar o keytab

O arquivo que esse script gera (ou um que o administrador do domínio já tenha) é enviado por aqui. Precisa cobrir todos os tipos de criptografia (\`-crypto All\`): o tipo real que o controlador de domínio vai usar não pode ser previsto de antemão, e um keytab que cobre só um tipo falha silenciosamente com clientes que negociam outro.

Sem um keytab enviado, o Kerberos não é oferecido mesmo estando marcado como ativado. Depois de enviá-lo (ou excluí-lo), é preciso **Aplicar alterações** para o Squid começar a usá-lo.
`.trim(),
}
